### ISSUE TITLE
LuckPerms incompatible with NeoForge for Minecraft 1.21

### ISSUE THREAD

**Issue by dimon7147** [LuckPerms/LuckPerms#3936]
### Description

LuckPerms Forge versions 5.4.133 and 5.4.134 are not compatible with NeoForge for Minecraft 1.21. The mod jar is being skipped during loading as it's detected as being for Minecraft Forge or an older version of NeoForge.

### Reproduction Steps

Install NeoForge 21.0.61-beta for Minecraft 1.21
Add LuckPerms-Forge-5.4.133.jar or LuckPerms-Forge-5.4.134.jar to the mods folder
Attempt to start the server
Observe the error in the logs

### Expected Behaviour

LuckPerms should load successfully with NeoForge for Minecraft 1.21

### Server Details

NeoForge 21.0.61-beta (MC: 1.21)

### LuckPerms Version

5.4.133 and 5.4.134 (both tested)

### Extra Details

Error message observed:
[main/WARN] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Skipping jar. File /home/servers/ATM10/mods/LuckPerms-Forge-5.4.133.jar is for Minecraft Forge or an older version of NeoForge, and cannot be loaded
This issue appears to be due to LuckPerms not yet being updated for compatibility with NeoForge and Minecraft 1.21.

**Comment by lucko** [comment]
LuckPerms does not (currently) have a release available for NeoForge. NeoForge is not the same as Forge.

**Comment by SawFowl** [comment]
NeoForge already has an API for permissions. Is support for this loader planned? The original Forge is already dying, many popular mods are no longer updated on it, they have moved to Neo.

**Comment by mindblaster0076** [comment]
Yes, support was added, but when you add it to your server, everyone just gets stuck on the "Joining World..." screen indefinitely despite the console saying you joined. I removed all other mods and tested without LP (Server worked fine and you were able to join) and with LP only (Issue described above occurred).

**Comment by 3TUSK** [comment]
> everyone just gets stuck on the "Joining World..." screen indefinitely despite the console saying you joined.

@mindblaster0076 Can you try again using LuckPerms v5.4.140? The said issue should be fixed now.

**Comment by Raul-Paiva** [comment]
The problem isn't solved! I can't enter my server when i have Luckperms installed. My server is running Neoforge 1.21.1

**Comment by SmileyDrag0n** [comment]
Running into the same problem myself, LP v5.4.158 on NeoForge 1.21.1

**Comment by serverside-swzo** [comment]
try using the 1.21.4 build of luckperms for neoforge, seems to work just fine on 1.21.1

**Comment by Gabrielsynapse** [comment]
deu certo baixar a versao 1.21.4 para o neoforge mais atual da 1.21.1

**Comment by am-clonec** [comment]
> deu certo baixar a versao 1.21.4 para o neoforge mais atual da 1.21.1
> 

Maybe speak English? Makes it more understandable.
